[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_BUILD_CACHE = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/yandex_3781a3df7bd9998e.html"
  to = "/yandex_3781a3df7bd9998e.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"